name: 'TfVars'
description: 'Updates a tfvars file'

inputs:
  version:
    description: 'The version to sync to'
    required: true
  tfvars-file:
    description: 'The path to the tfvars file to update'
    required: true
  scripts-version:
    description: 'The version of the scripts to use'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:

  - name: Download required scripts
    uses: Mcafee123/affolterNET.Github.SharedWorkflows/actions/get-scripts@main
    with:
      scripts: "scripts/ci_tf.sh scripts/ci_utils.sh"
      scripts-version: ${{ inputs.scripts-version }}

  - name: Sync tfvars with deployment version
    shell: bash
    run: |
      ./scripts/ci_tf.sh sync-tfvars ${{ inputs.version }} ${{ inputs.tfvars-file }}
