name: 'Check open PR'
inputs:
  github-token:
    description: 'GitHub token to access the repository and pull requests'
    required: true

outputs:
  pr_running_to_main:
    description: 'Whether there is an open PR from current branch to main'
    value: ${{ steps.check-pr.outputs.pr_running_to_main }}

runs:
  using: 'composite'
  steps:

  - name: Check Open PR Action Started
    shell: bash
    run: |
      echo "ðŸš€ Starting Check Open PR Action"
      echo "All inputs received:"
      echo "  - github-token: $([ -n '${{ inputs.github-token }}' ] && echo 'Provided' || echo 'Not provided')"
      echo "Context info:"
      echo "  - event_name: ${{ github.event_name }}"
      echo "  - ref_name: ${{ github.ref_name }}"
      echo "  - repository: ${{ github.repository }}"

  - name: Check for open PR to main
    id: check-pr
    if: github.event_name == 'push'
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github-token }}
    run: |
      # Check if there's an open PR from current branch to main
      pr_count=$(gh pr list --repo ${{ github.repository }} --head "${{ github.ref_name }}" --base main --json number | jq length)
      if [ "$pr_count" -gt 0 ]; then
        echo "pr_running_to_main=true" >> $GITHUB_OUTPUT
        echo "âš ï¸ Found open PR from ${{ github.ref_name }} to main - skipping workflow"
      else
        echo "pr_running_to_main=false" >> $GITHUB_OUTPUT
        echo "âœ… No open PR from ${{ github.ref_name }} to main - continuing workflow"
      fi

      # Debug info
      echo "Checked PRs from branch: ${{ github.ref_name }}"
