name: 'Checkout Code'
inputs:
  fetch-depth:
    description: 'Fetch depth for git history'
    required: false
    default: 1

runs:
  using: 'composite'
  steps:

    - name: Checkout Action Started
      shell: bash
      run: |
        echo "🚀 Starting Checkout Action"
        echo "All inputs received:"
        echo "  - fetch-depth: ${{ inputs.fetch-depth }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ github.head_ref || github.ref_name }}
        token: ${{ github.token }}

    - name: Debug checkout context
      shell: bash
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref_name }}"
        echo "Head Ref: ${{ github.head_ref }}"
        echo "Current commit: $(git rev-parse HEAD)"
        echo "Current branch: $(git branch --show-current)"
