# actions/load-config/action.yml
name: 'Load Application Configuration'
description: 'Loads and parses application configuration from JSON file'

inputs:
  config-file:
    description: 'Path to configuration JSON file'
    required: true
    default: '.github/config/app.json'

outputs:
  # Frontend outputs
  build-frontend:
    description: "Whether to build the frontend"
    value: ${{ steps.parse.outputs.build-frontend }}
  frontend-root:
    description: "Frontend root directory"
    value: ${{ steps.parse.outputs.frontend-root }}
  frontend-build-command:
    description: "Frontend build command"
    value: ${{ steps.parse.outputs.frontend-build-command }}
  node-version:
    description: "Node.js version"
    value: ${{ steps.parse.outputs.node-version }}
    
  # Backend outputs
  backend-root:
    description: "Backend root directory"
    value: ${{ steps.parse.outputs.backend-root }}
  backend-folder:
    description: "Backend project folder"
    value: ${{ steps.parse.outputs.backend-folder }}
  backend-project-file:
    description: "Backend project file"
    value: ${{ steps.parse.outputs.backend-project-file }}
    
  # Docker outputs
  image-name:
    description: "Docker image name"
    value: ${{ steps.parse.outputs.image-name }}
  registry-name:
    description: "Container registry name"
    value: ${{ steps.parse.outputs.registry-name }}
  dockerfile:
    description: "Dockerfile path"
    value: ${{ steps.parse.outputs.dockerfile }}
    
  # Terraform outputs
  tf-module-path:
    description: "Terraform module path"
    value: ${{ steps.parse.outputs.tf-module-path }}
  tfvars-file:
    description: "Terraform variables file"
    value: ${{ steps.parse.outputs.tfvars-file }}
    
  # Versioning outputs
  version-script:
    description: "Version management script"
    value: ${{ steps.parse.outputs.version-script }}
  scripts-version:
    description: "Scripts version to use"
    value: ${{ steps.parse.outputs.scripts-version }}
    
  # GitHub outputs
  tag-script:
    description: "Git tagging script"
    value: ${{ steps.parse.outputs.tag-script }}
  tag-prefix:
    description: "Git tag prefix"
    value: ${{ steps.parse.outputs.tag-prefix }}
  pr-running-to-main:
    description: "Whether there's an open PR to main"
    value: ${{ steps.check-pr.outputs.pr_running_to_main }}

runs:
  using: 'composite'
  steps:
    - name: Load and parse configuration
      id: parse
      shell: bash
      run: |
        # Check if config file exists
        if [ ! -f "${{ inputs.config-file }}" ]; then
          echo "❌ Configuration file not found: ${{ inputs.config-file }}"
          exit 1
        fi
        
        # Load JSON file
        CONFIG=$(cat "${{ inputs.config-file }}")
        
        # Validate JSON
        if ! echo "$CONFIG" | jq empty 2>/dev/null; then
          echo "❌ Invalid JSON in configuration file: ${{ inputs.config-file }}"
          exit 1
        fi
        
        # Debug: Show the loaded configuration
        echo "🔍 Loaded configuration:"
        echo "$CONFIG" | jq .
        
        # Extract values using jq and set as outputs
        echo "build-frontend=$(echo '$CONFIG' | jq -r '.frontend.buildFrontend // true')" >> $GITHUB_OUTPUT
        echo "frontend-root=$(echo '$CONFIG' | jq -r '.frontend.root // "frontend"')" >> $GITHUB_OUTPUT
        echo "frontend-build-command=$(echo '$CONFIG' | jq -r '.frontend.buildCommand // "npm run build"')" >> $GITHUB_OUTPUT
        echo "node-version=$(echo '$CONFIG' | jq -r '.frontend.nodeVersion // "20.x"')" >> $GITHUB_OUTPUT
        
        echo "backend-root=$(echo '$CONFIG' | jq -r '.backend.root')" >> $GITHUB_OUTPUT
        echo "backend-folder=$(echo '$CONFIG' | jq -r '.backend.folder')" >> $GITHUB_OUTPUT
        echo "backend-project-file=$(echo '$CONFIG' | jq -r '.backend.projectFile')" >> $GITHUB_OUTPUT
        
        echo "image-name=$(echo '$CONFIG' | jq -r '.docker.imageName')" >> $GITHUB_OUTPUT
        echo "registry-name=$(echo '$CONFIG' | jq -r '.docker.registryName')" >> $GITHUB_OUTPUT
        echo "dockerfile=$(echo '$CONFIG' | jq -r '.docker.dockerfile // "Dockerfile"')" >> $GITHUB_OUTPUT
        
        echo "version-script=$(echo '$CONFIG' | jq -r '.versioning.script')" >> $GITHUB_OUTPUT
        echo "scripts-version=$(echo '$CONFIG' | jq -r '.versioning.scriptsVersion // "main"')" >> $GITHUB_OUTPUT
        
        echo "tf-module-path=$(echo '$CONFIG' | jq -r '.terraform.modulePath')" >> $GITHUB_OUTPUT
        echo "tfvars-file=$(echo '$CONFIG' | jq -r '.terraform.tfvarsFile')" >> $GITHUB_OUTPUT
        
        echo "tag-script=$(echo '$CONFIG' | jq -r '.github.tagScript')" >> $GITHUB_OUTPUT
        echo "tag-prefix=$(echo '$CONFIG' | jq -r '.github.tagPrefix')" >> $GITHUB_OUTPUT
        
        # Debug: Show all extracted values
        echo "🔍 Extracted values:"
        echo "  Frontend:"
        echo "    - buildFrontend: $(echo '$CONFIG' | jq -r '.frontend.buildFrontend // true')"
        echo "    - root: $(echo '$CONFIG' | jq -r '.frontend.root // "frontend"')"
        echo "    - buildCommand: $(echo '$CONFIG' | jq -r '.frontend.buildCommand // "npm run build"')"
        echo "    - nodeVersion: $(echo '$CONFIG' | jq -r '.frontend.nodeVersion // "20.x"')"
        echo "  Backend:"
        echo "    - root: $(echo '$CONFIG' | jq -r '.backend.root')"
        echo "    - folder: $(echo '$CONFIG' | jq -r '.backend.folder')"
        echo "    - projectFile: $(echo '$CONFIG' | jq -r '.backend.projectFile')"
        echo "  Docker:"
        echo "    - imageName: $(echo '$CONFIG' | jq -r '.docker.imageName')"
        echo "    - registryName: $(echo '$CONFIG' | jq -r '.docker.registryName')"
        echo "    - dockerfile: $(echo '$CONFIG' | jq -r '.docker.dockerfile // "Dockerfile"')"
        echo "  Versioning:"
        echo "    - script: $(echo '$CONFIG' | jq -r '.versioning.script')"
        echo "    - scriptsVersion: $(echo '$CONFIG' | jq -r '.versioning.scriptsVersion // "main"')"
        echo "  Terraform:"
        echo "    - modulePath: $(echo '$CONFIG' | jq -r '.terraform.modulePath')"
        echo "    - tfvarsFile: $(echo '$CONFIG' | jq -r '.terraform.tfvarsFile')"
        echo "  GitHub:"
        echo "    - tagScript: $(echo '$CONFIG' | jq -r '.github.tagScript')"
        echo "    - tagPrefix: $(echo '$CONFIG' | jq -r '.github.tagPrefix')"
        
    - name: Check for open PR to main
      id: check-pr
      if: github.event_name == 'push'
      uses: Mcafee123/affolterNET.Github.SharedWorkflows/actions/check-open-pr@main
      with:
        github-token: ${{ github.token }}
