name: 'Get Latest ACR Version'
description: 'Get the latest Docker image tag from Azure Container Registry'
inputs:
  registry-name:
    description: 'ACR registry name (without .azurecr.io)'
    required: true
  repository:
    description: 'Image repository name (e.g., an-formsg-api)'
    required: true
  tag-pattern:
    description: 'Optional regex pattern to filter tags (e.g., ^[0-9]+\.[0-9]+\.[0-9]+$)'
    required: false
    default: ''
outputs:
  version:
    description: 'Latest version/tag found'
    value: ${{ steps.get-version.outputs.version }}
  
runs:
  using: 'composite'
  steps:
    - name: Get latest version from ACR
      id: get-version
      shell: bash
      run: |
        # Login already handled by calling workflow
        
        if [ -n "${{ inputs.tag-pattern }}" ]; then
          # Get tags matching pattern
          TAGS=$(az acr repository show-tags \
            --name ${{ inputs.registry-name }} \
            --repository ${{ inputs.repository }} \
            --orderby time_desc \
            --output tsv)
          
          # Filter by pattern and get first match
          LATEST_TAG=$(echo "$TAGS" | grep -E "${{ inputs.tag-pattern }}" | head -1)
        else
          # Get latest tag (most recent)
          LATEST_TAG=$(az acr repository show-tags \
            --name ${{ inputs.registry-name }} \
            --repository ${{ inputs.repository }} \
            --orderby time_desc \
            --top 1 \
            --output tsv)
        fi
        
        if [ -z "$LATEST_TAG" ]; then
          echo "❌ No matching tags found in ACR"
          exit 1
        fi
        
        echo "✅ Latest tag: $LATEST_TAG"
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT