name: Update Version

runs:
  using: 'composite'
  steps:
  - name: Update version
    id: version
    run: |
      echo "Updating version using: ./${{ inputs.version-script }} update ${{ inputs.project-root }}/${{ inputs.project-folder }}/${{ inputs.project-file}} ${{ inputs.tfvars-file }}"
      ./${{ inputs.version-script }} update ${{ inputs.project-root }}/${{ inputs.project-folder }}/${{ inputs.project-file}} ${{ inputs.tfvars-file }}
