name: 'Get Version- and Tag-Scripts'
description: 'Downloads and sets up common build scripts from shared repository'
inputs:
  scripts-version:
    description: 'Version/tag of scripts to use'
    required: false
    default: 'main'
  github-token:
    description: 'GitHub token for accessing private repositories'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Download and verify scripts from shared repository
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO_OWNER: McAfee123
        REPO_NAME: affolterNET.Github.SharedWorkflows
        SCRIPTS_VERSION: ${{ inputs.scripts-version }}
      run: |
        echo "📥 Downloading scripts from shared repository..."
        
        # Create scripts directory if it doesn't exist
        mkdir -p scripts
        
        # List of scripts to download - defined once and reused
        SCRIPTS=(
          "ci_version.sh"
          "ci_tag.sh"
        )
        
        # Download scripts
        for script in "${SCRIPTS[@]}"; do
          # Clean up existing version if it exists
          if [ -f "scripts/$script" ]; then
            echo "🧹 Removing existing scripts/$script..."
            rm "scripts/$script"
          fi
          
          echo "Downloading $script..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/contents/scripts/$script?ref=$SCRIPTS_VERSION" \
               -o "scripts/$script"
          
          # Make script executable
          chmod +x "scripts/$script"
          echo "✅ Downloaded and set executable: scripts/$script"
        done
        
        echo "✅ All scripts downloaded successfully"
        
        # Verify the downloaded scripts
        echo "🔍 Verifying downloaded scripts..."
        ls -la scripts/
        
        # Basic validation - using the same SCRIPTS array
        for script in "${SCRIPTS[@]}"; do
          script_path="scripts/$script"
          if [ -f "$script_path" ] && [ -x "$script_path" ]; then
            echo "✅ $script_path - OK (executable)"
          else
            echo "❌ $script_path - FAILED (not found or not executable)"
            exit 1
          fi
        done
        
        echo "✅ All scripts verified successfully"