name: Version Update

on:
  workflow_call:
    inputs:
      project-root:
        required: true
        type: string
      project-folder:
        required: true
        type: string
      project-file:
        required: true
        type: string
      tfvars-file:
        required: false
        type: string
        default: ''
      version-script:
        required: false
        type: string
        default: './scripts/ci_version.sh'
        description: 'Path to version script downloaded from shared repository'
      scripts-version:
        required: false
        type: string
        default: 'main'
        description: 'Version/tag of scripts to use from shared repository'
jobs:
  version-update:
    name: ${{ inputs.project-file }}
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ github.token }}

    - name: Get version scripts
      uses: ./actions/get-scripts
      with:
        scripts-version: ${{ inputs.scripts-version }}
        github-token: ${{ github.token }}

    - name: Update version
      id: version
      run: |
        echo "Updating version using: ./${{ inputs.version-script }} update ${{ inputs.project-root }}/${{ inputs.project-folder }}/${{ inputs.project-file}} ${{ inputs.tfvars-file }}"
        ./${{ inputs.version-script }} update ${{ inputs.project-root }}/${{ inputs.project-folder }}/${{ inputs.project-file}} ${{ inputs.tfvars-file }}
